version: '3.8'
services:
  db:
    image: postgres:11.18-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - '5432:5432'
    volumes: 
      - dbVolume:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:1.3.0
    restart: always
    environment: 
      - AWS_DEFAULT_REGION=us-east-1
      - EDGE_PORT=4566
      - SERVICES=s3
    ports: 
      - '4566-4583:4566-4583'
    volumes: 
      - "localstackVolume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  dbVolume:
    name: dbVolume
    driver: local
  localstackVolume:
    name: localstackVolume
    driver: local
